/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_papan01_livestreamer_Live555Native */

#ifndef _Included_edu_papan01_livestreamer_Live555Native
#define _Included_edu_papan01_livestreamer_Live555Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_papan01_livestreamer_Live555Native
 * Method:    initialize
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_segway_robot_module_stream_Live555Native_initialize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     edu_papan01_livestreamer_Live555Native
 * Method:    loopNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_segway_robot_module_stream_Live555Native_loopNative
  (JNIEnv *, jobject);

/*
 * Class:     edu_papan01_livestreamer_Live555Native
 * Method:    stopNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_segway_robot_module_stream_Live555Native_stopNative
  (JNIEnv *, jobject);

/*
 * Class:     edu_papan01_livestreamer_Live555Native
 * Method:    feedH264Data
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_segway_robot_module_stream_Live555Native_feedH264Data
  (JNIEnv *, jobject, jbyteArray);
    
 
JNIEXPORT void JNICALL Java_com_segway_robot_module_stream_Live555Native_feedAACAudioData
  (JNIEnv *, jobject, jbyteArray);
    

/*
 * Class:     edu_papan01_livestreamer_Live555Native
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_segway_robot_module_stream_Live555Native_destroy
  (JNIEnv *, jobject);
    
JNIEXPORT void JNICALL Java_com_segway_robot_module_stream_Live555Native_addListener
  (JNIEnv *, jobject, jobject);
    
    
JNIEXPORT void JNICALL Java_com_segway_robot_mobile_network_stream_Live555Client_addBufferListener
    (JNIEnv *, jobject, jobject);
    
JNIEXPORT void JNICALL Java_com_segway_robot_mobile_network_stream_Live555Client_playRTSP
    (JNIEnv *, jobject, jstring);
    
JNIEXPORT void JNICALL Java_com_segway_robot_mobile_network_stream_Live555Client_stopRTSP
    (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
